name: publish to nuget
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Test
        run: dotnet test -c Release --no-build --no-restore

      - name: Package
        run: |
          cd src
          dotnet pack -c Release -o . CommonCommons.csproj

      - name: Publish
        run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json